env: flex
runtime: nodejs
env_variables:
  SQL_USER: root
  SQL_PASSWORD: secret
  SQL_DATABASE: rsdb
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: feisty-beacon-180520:us-east1:reportingservice
  beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: feisty-beacon-180520:us-east1:reportingservice